#!/bin/bash
# Install the Plotly Dash JupyterLab extension
jupyter labextension install @plotly/jupyterlab-dash --no-build
# Rebuild JupyterLab to apply the new extension
jupyter lab build --minimize=False


